# Generated by Django 3.1 on 2020-09-04 06:36

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200904_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=product.models.save_dir),
        ),
    ]
