# Generated by Django 3.1 on 2020-09-11 06:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200909_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
