# Generated by Django 3.1 on 2020-09-11 06:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productrating_properties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='properties',
        ),
        migrations.AddField(
            model_name='category',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
