# Generated by Django 3.1 on 2020-09-11 07:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200911_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
