# Generated by Django 3.1.1 on 2020-10-01 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import first_project.costom_field
import product.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Phone_number',
            field=first_project.costom_field.CustomBigIntegerField(unique=True, validators=[product.validators.PhoneNumberValidator()], verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('verification_code', models.PositiveIntegerField(verbose_name='verification code')),
                ('verify_time', models.DateTimeField(blank=True, null=True, verbose_name='verify_time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verify_codes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'verify code',
                'verbose_name_plural': 'verify codes',
            },
        ),
    ]
