# Generated by Django 3.1.1 on 2020-10-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201001_1428'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='verifycode',
            index=models.Index(fields=['user', 'verification_code'], name='index_user_code'),
        ),
    ]
